Wellbores_Tab    =   "id=wellbores"
Well_bores_Name_DD_Arrow = "//div[@class='filter-category']//input[@placeholder='Select filter category' and @id='mat-input-2']/parent::div//*[local-name()='svg']"
Well_bores_Select_pad_name_from_dd ="xpath=//span[text()='value']"
Well_bores_Search_input_locator = "xpath=//input[@id='mat-input-3' and @class='mat-mdc-input-element filter-value cdk-text-field-autofill-monitored']"
Well_bores_Apply_Filter = "xpath=//input[@id='mat-input-3']//following-sibling::div//button[contains(text(),'Apply Filters')]"
Well_bores_Side_Extend_Tab= "xpath=(//div[@class='main-table-container']//app-details-form-window/div/div[@class='expand-tab'])[2]"
Well_bores_Table_only_Wellname_Value ="xpath=//tr[@id='wellbores_wellRow_0']//td"
Well_bores_Ex_Tab_Pad_data_Comments ="xpath=//button[contains(text(),'Comments') ]"
Well_bores_Ex_Tab_Pad_data_Comments_Input ="xpath=//textarea[@placeholder='Add a comment ...']"
Well_bores_Ex_Tab_Pad_data_Comments_Post_btn ="xpath=//button[contains(text(),' Post ')]"
Well_bores_Ex_Tab_Pad_data_Comments_lists ="xpath=//div[@class='comment-text']"
Well_bores_Table_Headings_Locatore="xpath=((//table[@class='mat-mdc-table mdc-data-table__table cdk-table table']//thead//tr)[2]//th)"
Well_bores_Table_Datas_Locatore="xpath=((//table[@class='mat-mdc-table mdc-data-table__table cdk-table table']//tbody)[2]//td)"
Well_bores_Table_Rows_Locatore="xpath=(//table[@class='mat-mdc-table mdc-data-table__table cdk-table table']//tbody)[2]//tr"
Well_bores_Table_Each_data_Locatore="xpath=(//table[@class='mat-mdc-table mdc-data-table__table cdk-table table']//tbody)[2]//tr[RowIndex]//td[DataIndex]"