Login_page_username = "id=i0116"
Login_Page_username_next_btn = "id=idSIButton9"
Login_page_password = "id=i0118"
Login_page_login_btn = "idSIButton9"
Login_Page_WellData_btn="xpath=//h2[text()='Well Data']"
