Pads_Tab    =   "id=pads"
Pad_Name_DD_Arrow = "xpath=//*[local-name()='svg' and @fill='none']"
Pad_Select_pad_name_from_dd ="xpath=//span[contains(text(),'Pad Name')]"
Pad_Search_input = "id=mat-input-3"
Pads_DD_Search_Box = "id=mat-input-2"
Pads_Apply_Filter = "xpath=//input[@id='mat-input-3']//following-sibling::div//button[contains(text(),'Apply Filters')]"
Pads_Refresh_Table = "xpath=//input[@id='mat-input-14']//following-sibling::div//p"
Pads_And_Toggle = "xpath=//button[@id='mat-button-toggle-7-button' or @class='mat-button-toggle-button mat-focus-indicator' and @name='mat-button-toggle-group-3']/span[contains(text(),'And')]"
Pads_Or_Toggle = "xpath=//button[@id='mat-button-toggle-8-button']/span[contains(text(),'Or')]"
Pads_And_Toggle_Pressed_status= "xpath=//button[@id='mat-button-toggle-7-button' or @class='mat-button-toggle-button mat-focus-indicator' and @name='mat-button-toggle-group-3']/span[contains(text(),'And')]//parent::button]"
Pads_Table_All_Option = "xpath=//div[@id='mat-tab-label-4-0']"
Pads_Table_Eagleford  = "xpath=//div[@id='mat-tab-label-4-1']/span/span[contains(text(),'Eagleford')]"
Pads_Table_Haynesville = "xpath=//div[@id='mat-tab-label-4-2']/span/span[contains(text(),'Haynesville')]"
Pads_Table_Permian = "xpath=//div[@id='mat-tab-label-4-3']/span/span[contains(text(),'Permian')]"
Pads_Table = "xpath=//th[contains(text(),'pad ID') and @role='columnheader']//parent::tr//parent::thead//parent::table"
Pads_Table_only_Padname_Value ="xpath=//th[contains(text(),'pad ID') and @role='columnheader']//parent::tr//parent::thead//parent::table//tr//td[@class='mat-mdc-cell mdc-data-table__cell cdk-cell cell cdk-column-pad_name mat-column-pad_name ng-star-inserted']"
Pads_Table_Rows ="xpath=//th[contains(text(),'pad ID') and @role='columnheader']//parent::tr//parent::thead//parent::table//th"
Pads_Table_coloum= "xpath=//th[contains(text(),'pad ID') and @role='columnheader']//parent::tr//parent::thead//parent::table//tr"
Pads_Table_all_values_elements ="xpath=//th[contains(text(),'pad ID') and @role='columnheader']//parent::tr//parent::thead//parent::table//tr//td"
Pads_Data_Portal_Well_List = "//div[@class='main-table-container']//app-details-form-window/div/button"
Pads_Side_Extend_Tab = "//div[@class='main-table-container']//app-details-form-window/div/div[@class='expand-tab']"
Pads_Extend_Tab_Close_btn = "//button[@class='close-button secondary']"
Pads_Ex_tab_Title = "xpath=//h1[contains(text(),'{well_name}')]"
Pads_Ex_Tab_Pad_data_selection = "xpath=//span[@class='mat-content ng-tns-c2690051721-22']/mat-panel-title[contains(text(),'Pad Data')]"
Pads_Ex_Tab_Front_End_Loading = "xpath=//span[@class='mat-content ng-tns-c2690051721-24']/mat-panel-title[contains(text(),'Front End')]"
Pads_Ex_Tab_Pad_data_info = "xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]"
Pads_Ex_Tab_Pad_data_Comments ="xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Comments')]"
Pads_Ex_Tab_Pad_data_History = "xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'History')]"
Pads_Ex_Tab_Pad_data_Attachemnts ="xpath=//div[@id='cdk-accordion-child-4'  or  @class='mat-expansion-panel-content ng-tns-c1859850774-13 ng-trigger ng-trigger-bodyExpansion']/div/button[contains(text(),'Attachments')]"
Pads_Ex_Tab_Fr_loading_Details ="xpath=//div[@id='cdk-accordion-child-5']/div/button[contains(text(),'Details')]"
Pads_Ex_Tab_Fr_loading_Subsurfaces = "xpath=//div[@id='cdk-accordion-child-5']/div/button[contains(text(),'Subsurface')]"
Pads_Ex_Tab_Fr_loading_Surface_Land = "xpath=//div[@id='cdk-accordion-child-5']/div/button[contains(text(),'Surface')]"
Pads_Ex_Tab_Fr_loading_Survey = "xpath=//div[@id='cdk-accordion-child-5']/div/button[contains(text(),'Survey')]"
Pads_Ex_Tab_Fr_loading_Regulatory ="xpath=//div[@id='cdk-accordion-child-5']/div/button[contains(text(),'Regulatory')]"
Pads_Ex_Tab_Header_Table="xpath=(//table[@class='mat-mdc-table mdc-data-table__table cdk-table table'])[2]"
Pads_Ex_Tab_Pad_data_Dashboard_Header = "xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]/parent::div//parent::div//parent::mat-expansion-panel//parent::mat-accordion//parent::div/parent::app-navigation-menu//following-sibling::div[@class='body-content']/h2"
Pads_Ex_Tab_Pad_data_info_Dashboard_Labels = "xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]/parent::div//parent::div//parent::mat-expansion-panel//parent::mat-accordion//parent::div/parent::app-navigation-menu//following-sibling::div[@class='body-content']//div[@class='label-container']/label"
Pads_Ex_Tab_Pad_data_info_PAD_name_label = "xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]/parent::div//parent::div//parent::mat-expansion-panel//parent::mat-accordion//parent::div/parent::app-navigation-menu//following-sibling::div[@class='body-content']//div[@class='label-container']/label[contains(text(),'pad name')]"
Pads_Ex_Tab_Pad_data_info_PAD_ID_label = "xpath=//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]/parent::div//parent::div//parent::mat-expansion-panel//parent::mat-accordion//parent::div/parent::app-navigation-menu//following-sibling::div[@class='body-content']//div[@class='label-container']/label[contains(text(),'pad id')]"
#This Xpath contains 6 Tooltips icon for mouse hover
Pads_Ex_Tab_Pad_data_info_Dashboard_Tooltips_icons ="//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]/parent::div//parent::div//parent::mat-expansion-panel//parent::mat-accordion//parent::div/parent::app-navigation-menu//following-sibling::div[@class='body-content']//div[@class='label-container']/div[@class='tooltip-container ng-star-inserted']"
#This Xpath contains 6 Tooltips Values get Tooltip value
Pads_Ex_Tab_Pad_data_info_Dashboard_Tooltips_Value = "//div[@id='cdk-accordion-child-4']/div/button[contains(text(),'Info')]/parent::div//parent::div//parent::mat-expansion-panel//parent::mat-accordion//parent::div/parent::app-navigation-menu//following-sibling::div[@class='body-content']//div[@class='label-container']/div[@class='tooltip-container ng-star-inserted']//p"
Pads_Ex_Tab_Pad_data_info_PAD_name_Input ="xpath=//input[@id='Pad_Data-Info-pad_name']"
Pads_Ex_Tab_Pad_data_info_PAD_ID_Input = "xpath=//input[@id='Pad_Data-Info-pad_id']"
Pads_Ex_Tab_Pad_data_info_well_origins_Values ="xpath=//div[@id='Pad_Data-Info-well_origins']/a"
Pads_Ex_Tab_Pad_data_info_Business_unit_input = "xpath=//input[@id='Pad_Data-Info-business_unit']"
Pads_Ex_Tab_Pad_data_info_BU_DSO_input = "//input[@id='Pad_Data-Info-bu_dso']"
Pads_Ex_Tab_Pad_data_info_STATE_input =  "//input[@id='Pad_Data-Info-state']"
Pads_Ex_Tab_Pad_data_comments_add_comment = "xpath=//div[@class='new-comment-input']"
Pads_Ex_Tab_Pad_data_comments_post_btn = "xpath=//div[@class='new-comment-section']/button"

#Below xpath will focus on History headers & date
Pads_Ex_Tab_Pad_data_History_Headers = "xpath=//div[@class='history-header']//span"
Pads_Ex_Tab_Pad_data_History_texts = "xpath=//div[@class='history-text']//span"
Pads_Ex_Tab_Pad_data_Attachements_first_upload_area = "xpath=//label[contains(text(),'attachments')]/parent::div/parent::div/app-file-upload/section/div/div/input[@id='file-input']"
Pads_Ex_Tab_Pad_data_Attachements_first_URL_name_input = "xpath=(//input[@placeholder='URL Name'])[1]"
Pads_Ex_Tab_Pad_data_Attachements_first_URL_input ="xpath=(//input[@placeholder='URL'])[1]"
Pads_Ex_Tab_Pad_data_Attachements_first_upload_URL_btn = "xpath=(//button[@class='upload-url-btn'])[1]"
#Below xpath will contain all uploaded files link/name
Pads_Ex_Tab_Pad_data_Attachements_first_uploaded_doc_name ="xpath=//section[@id='uploaded-files-section']//span[@class='file-link']"
Pads_Ex_Tab_Pad_data_Attachements_first_uploaded_doc_details = "xpath=//section[@id='uploaded-files-section']//span[@class='property-value']"

Pads_Ex_Tab_Ft_nd_ld_Details_spa_input ="xpath=//textarea[@id='Front_End_Loading-Details-spa']"
Pads_Ex_Tab_Ft_nd_ld_Details_Surveyor_input = "xpath=//input[@id='Front_End_Loading-Details-surveyor']"
Pads_Ex_Tab_Ft_nd_ld_Details_Surface_negotiator_input = "xpath=//textarea[@id='Front_End_Loading-Details-surface_negotiator']"



