Wellbores_Tab    =   "id=wellbores"
Well_bores_Name_DD_Arrow = "xpath=(//*[local-name()='svg' and @fill='none'])[4]"
Well_bores_Select_pad_name_from_dd ="xpath=//span[text()='value']"
Well_bores_Search_input = "xpath=//input[@id='mat-input-3' and @class='mat-mdc-input-element filter-value cdk-text-field-autofill-monitored']"
Well_bores_Apply_Filter = "xpath=//input[@id='mat-input-3']//following-sibling::div//button[contains(text(),'Apply Filters')]"
Well_bores_Side_Extend_Tab= "xpath=(//div[@class='main-table-container']//app-details-form-window/div/div[@class='expand-tab'])[2]"
Well_bores_Table_only_Wellname_Value ="xpath=//tr[@id='wellbores_wellRow_0']//td"
Well_bores_Ex_Tab_Pad_data_Comments ="xpath=//button[contains(text(),'Comments') ]"
Well_bores_Ex_Tab_Pad_data_Comments_Input ="xpath=//textarea[@placeholder='Add a comment ...']"
Well_bores_Ex_Tab_Pad_data_Comments_Post_btn ="xpath=//button[contains(text(),' Post ')]"
Well_bores_Ex_Tab_Pad_data_Comments_lists ="xpath=//div[@class='comment-text']"