Completions_Tab    =   "id=completions"
Completions_Name_DD_Arrow = "xpath=(//*[local-name()='svg' and @fill='none'])[7]"
Completions_Select_pad_name_from_dd ="xpath=//span[text()='value']"
Completions_Search_input = "xpath=//input[@id='mat-input-5' and @class='mat-mdc-input-element filter-value cdk-text-field-autofill-monitored']"
Completions_Apply_Filter = "xpath=//input[@id='mat-input-5']//following-sibling::div//button[contains(text(),'Apply Filters')]"
Completions_Table_only_Wellname_Value ="xpath=//tr[@id='completions_wellRow_0']//td"
Completions_Side_Extend_Tab= "xpath=(//div[@class='main-table-container']//app-details-form-window/div/div[@class='expand-tab'])[3]"
Completions_Ex_tab_Title = "xpath=//h1[contains(text(),'value')]"
Completions_Ex_Tab_Header_Table_Values="xpath=(//table[@class='mat-mdc-table mdc-data-table__table cdk-table table'])[4]//td"
Completions_Ex_Tab_Pad_data_info_all_information_inputs ="xpath=//form//input"
completions_Ex_Tab_info_tab_informations_Origin_Corp_ID=  "xpath=//div[@id='Completion_Data-Info-origin_corp_id']/a"
completions_Ex_Tab_info_tab_informations_Wellbore_Corp_ID=  "xpath=//div[@id='Completion_Data-Info-wellbore_corp_id']/a"
