Login_page_username = "id=user_username"
Login_page_password = "id=user_password"
Login_page_signIn_btn = "id=signIn"
Login_page_cancel_btn = "id=cancel"
ArcGIS_Login_Title=   "id=loginTitle"
ArcGIS_Menu_btn= "xpath=//button[@class='dropdown-btn toggle btn btn-large btn-no-style']"
#Below xpath in value field have to replace with our original selection value
DD_Value_Selection= "xpath=//div[@class='dropdown-menu is-active popper']//label/span[text()='value']"
Business_Unit_DD_Click_btn = "xpath=//span[@title='Business Unit']"
Facility_DD_Click_btn= "xpath=//span[@title='Facility']"
Gateway_DD_Click_btn= "xpath=//span[@title='Gateway']"
Sensor_status_Value_Set= "xpath=(//div[@class='widget-body flex-fluid full-width flex-vertical overflow-y-auto overflow-x-hidden']//div[@class='external-html'])[index]"
Sensor_status_values= "xpath=//div[@class='widget-body flex-fluid full-width flex-vertical overflow-y-auto overflow-x-hidden']//div[@class='external-html']/p"
NS_Online_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[1]//*[local-name()='text' ]"
GW_Online_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[2]//*[local-name()='text' ]"
Alarmed_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[3]//*[local-name()='text' ]"
