Login_page_username = "id=user_username"
Login_page_password = "id=user_password"
Login_page_signIn_btn = "id=signIn"
Login_page_cancel_btn = "id=cancel"
Login_Page_Title_Value=  "xpath=//*[@id='loginTitle']"
