Login_page_username = "id=user_username"
Login_page_password = "id=user_password"
Login_page_signIn_btn = "id=signIn"
Login_page_cancel_btn = "id=cancel"
ArcGIS_Login_Title=   "id=loginTitle"
ArcGIS_Menu_btn= "xpath=//button[@class='dropdown-btn toggle btn btn-large btn-no-style']"
#Below xpath in value field have to replace with our original selection value
DD_Value_Selection= "xpath=//div[@class='dropdown-menu is-active popper']//label/span[text()='value']"
Business_Unit_DD_Click_btn = "xpath=//span[@title='Business Unit']"
Facility_DD_Click_btn= "xpath=//span[@title='Facility']"
Gateway_DD_Click_btn= "xpath=//span[@title='Gateway']"
Sensor_status_Value_Set= "xpath=(//div[@class='widget-body flex-fluid full-width flex-vertical overflow-y-auto overflow-x-hidden']//div[@class='external-html'])[index]"
Sensor_status_values= "xpath=//div[@class='widget-body flex-fluid full-width flex-vertical overflow-y-auto overflow-x-hidden']//div[@class='external-html']/p"
NS_Online_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[1]//*[local-name()='text' ]"
GW_Online_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[2]//*[local-name()='text' ]"
Alarmed_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[3]//*[local-name()='text' ]"
Graph_point= "xpath=(//*[local-name()='svg']//*[name()='g' and  contains(@class,'amcharts-graph-line amcharts-graph-graphAuto0_170')])[2]//*[name()='circle']"
Expand_btn="xpath=//a[@class='dock-expand']//*[local-name()='svg']"
Graph_point2= "xpath=((//*[local-name()='svg']//*[name()='g' and  contains(@class,'amcharts-graph-line amcharts-graph-graphAuto0_170')])[2]//*[name()='circle'])[index]"
Graph_Wind_btn="xpath=//div[text()='Wind']"
Graph_Power_btn="xpath=//div[text()='Power']"
Graph_Scada_btn="xpath=//div[text()='SCADA']"
Graph_value_Fetch_AirQuality_MethenePPM= "xpath=//p[contains(text(),'Methane (PPM)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle']"
Graph_value_Fetch_AirQuality_Methene_VDC= "xpath=//p[contains(text(),'Methane (VDC)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle']"
Graph_Value_Fetch_AirQuality_Ambient_Temp_C= "xpath=//p[contains(text(),'Ambient Temp (C)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle']"
Graph_Value_Fetch_Wind_WindSpeed=  "xpath=(//p[contains(text(),'Wind Speed (mph - m/s)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle'])"
Graph_Value_Fetch_Wind_WindDirection = "xpath=(//p[contains(text(),'Wind Direction (Degrees)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle'])"
Graph_Value_Fetch_Power_Solar_CurrentA=  "xpath=//p[contains(text(),'Solar Current (A)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle']"
Graph_Value_Fetch_Power_Solar_VoltageVDC= "xpath=//p[contains(text(),'Solar Voltage (VDC)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle']"
Graph_Value_Fetch_Power_Battery_CurrentA= "//p[contains(text(),'Battery Current (A)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle']"
Graph_Value_Fetch_Power_Battery_VoltageVDC= "(//p[contains(text(),'Battery Voltage (VDC)')]/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle'])"
Graph_Value_Fetch_Scada_LEL= "xpath=(//span[contains(text(),'LEL')]//parent::p/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle'])"
Graph_Value_Fetch_Scada_H2S=  "xpath=(//span[contains(text(),'H2S (ppm)')]//parent::p/parent::div/parent::div[@class='flex-fix widget-header']/following-sibling::div/div//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto')]//*[name()='circle'])"
Map_Bookmark_btn= "xpath=//button[@class='btn btn-clear']//span[@class='icon-element rtl-mirror'][1]"
Map_Bookmark_List_Selection= "xpath=//span[@class='esri-bookmarks__bookmark-name' and contains(text(),'value')]"
Map_Bookmark_default_map_Extent_btn = "xpath=//span[@class='flex-fluid overflow-hidden font-size--2 text-ellipsis']"
Sensor_status_No_data = "xpath=//strong[contains(text(),'Sensor Status')]/parent::h3/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Air_Quality_MethaneVDC_No_data_Text= "xpath=//p[contains(text(),'Methane (VDC)')]/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Air_Quality_MethanePPM_No_data_Text= "xpath=//p[contains(text(),'Methane (PPM)')]/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Air_Quality_Ambient_TempC_No_data_Text= "xpath=//p[contains(text(),'Ambient Temp (C)')]/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Wind_WindSpeed_No_data_Text= "xpath=//p[contains(text(),'Wind Speed (mph - m/s)')]/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Wind_WindDirection_No_data_Text= "xpath=//p[contains(text(),'Wind Direction (Degrees)')]/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Scada_LEL_No_data_Text= "xpath=//span[contains(text(),'LEL')]/parent::p/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
Scada_H2S_No_data_Text= "xpath=//span[contains(text(),'H2S (ppm)')]/parent::p/parent::div/parent::div/following-sibling::div[@class='flex-fluid flex-vertical overflow-y-auto justify-content-center']//p"
