Login_page_username = "id=user_username"
Login_page_password = "id=user_password"
Login_page_signIn_btn = "id=signIn"
Login_page_cancel_btn = "id=cancel"
ArcGIS_Login_Title=   "id=loginTitle"
ArcGIS_Menu_btn= "xpath=//button[@class='dropdown-btn toggle btn btn-large btn-no-style']"
#Below xpath in value field have to replace with our original selection value
DD_Value_Selection= "xpath=//div[@class='dropdown-menu is-active popper']//label/span[text()='value']"
Business_Unit_DD_Click_btn = "xpath=//span[@title='Business Unit']"
Facility_DD_Click_btn= "xpath=//span[@title='Facility']"
Gateway_DD_Click_btn= "xpath=//span[@title='Gateway']"
Sensor_status_Value_Set= "xpath=(//div[@class='widget-body flex-fluid full-width flex-vertical overflow-y-auto overflow-x-hidden']//div[@class='external-html'])[index]"
Sensor_status_values= "xpath=//div[@class='widget-body flex-fluid full-width flex-vertical overflow-y-auto overflow-x-hidden']//div[@class='external-html']/p"
NS_Online_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[1]//*[local-name()='text' ]"
GW_Online_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[2]//*[local-name()='text' ]"
Alarmed_Count ="xpath=(//div[@class='responsive-text flex-vertical flex-fix allow-shrink indicator-center-text'])[3]//*[local-name()='text' ]"
Graph_point= "xpath=(//*[local-name()='svg']//*[name()='g' and  contains(@class,'amcharts-graph-line amcharts-graph-graphAuto0_170')])[2]//*[name()='circle']"
Expand_btn="xpath=//a[@class='dock-expand']//*[local-name()='svg']"
Graph_point2= "xpath=((//*[local-name()='svg']//*[name()='g' and  contains(@class,'amcharts-graph-line amcharts-graph-graphAuto0_170')])[2]//*[name()='circle'])[index]"
Graph_Wind_btn="xpath=//div[text()='Wind']"
Graph_Power_btn="xpath=//div[text()='Power']"
Graph_Scada_btn="xpath=//div[text()='SCADA']"
Graph_value_Fetch_AirQuality_MethenePPM= "xpath=(//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto2_17043')])[4]//*[name()='circle']"
Graph_value_Fetch_AirQuality_Methene_VDC= "xpath=(//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto0_170')])[2]//*[name()='circle']"
Graph_Value_Fetch_AirQuality_Ambient_Temp_C= "xpath=(//*[local-name()='svg']//*[name()='g' and contains(@class,'amcharts-graph-line amcharts-graph-graphAuto0_170')])[6]//*[name()='circle']"
